---
- name: Install Elasticsearch using Helm
  hosts: master
  become: yes
  tasks:
    - name: Create the ArgoCD namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        metadata:
          name: efk-monitoring

    - name: Ensure Python pip is installed
      apt:
        name: python3-pip
        state: present

    - name: Install Kubernetes Python client
      pip:
        name: kubernetes
        state: present

    - name: Add Helm repository for Elasticsearch
      shell: |
        helm repo add elastic https://helm.elastic.co
        helm repo update
      register: helm_repo_result
      changed_when: false

    - name: Install Elasticsearch using Helm
      shell: |
        helm install elasticsearch elastic/elasticsearch --version 7.17.3 -n efk-monitoring --set persistence.enabled=false,replicas=1
      register: helm_install_result

    - name: Print Helm installation result
      debug:
        var: helm_install_result.stdout_lines
