replicaCount: 2

mongo:
  image: mongo:latest
  storage: 1Gi

userService:
  image:
    repository: sganesamoorthy/customer-service
    tag: latest
  port: 8081
  env:
    SPRING_PROFILES_ACTIVE: docker
    SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/userdb

productService:
  image:
    repository: sganesamoorthy/project-service
    tag: latest
  port: 8082
  env:
    SPRING_PROFILES_ACTIVE: docker
    SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/productdb

ingress:
  enabled: true
  http:
    paths:
      - path: /users(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: userService
            port:
              number: 8081
      - path: /products(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: productService
            port:
              number: 8082
      - path: /addProject.html
        pathType: ImplementationSpecific
        backend:
          service:
            name: productService
            port:
              number: 8082
      - path: /addCustomer.html
        pathType: ImplementationSpecific
        backend:
          service:
            name: userService
            port:
              number: 8081
